#!/usr/bin/env python3
"""Materialize archived diagnostic tables used in the manuscript.

The headline simulation tables are generated by the experiment scripts with
raw per-replication outputs. These compact diagnostic tables are archived
summaries from earlier calibration runs; this script writes those summaries to
CSV so the numerical diagnostics have explicit package artifacts and can be
checked against the text. It is intentionally a static materialization step,
not a full stochastic replay of those calibration runs.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def write_csv(output_dir: Path, path: str, fieldnames: list[str], rows: list[dict[str, object]]) -> None:
    with (output_dir / path).open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT,
        help="Directory where diagnostic CSV files are written.",
    )
    args = parser.parse_args()
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    write_csv(
        output_dir,
        "diagnostic_provenance.csv",
        [
            "artifact",
            "manuscript_location",
            "role",
            "reproducibility_level",
            "package_boundary",
        ],
        [
            {
                "artifact": "surrogate_fidelity_summary.csv",
                "manuscript_location": "Supplementary Section 7 diagnostic",
                "role": "Numerical audit for the Gaussian-proxy bridge used under Assumption 1",
                "reproducibility_level": "Archived calibration summary materialized by archived_diagnostic_tables.py",
                "package_boundary": "The package does not include the full data-augmentation replay for this archived calibration run.",
            },
            {
                "artifact": "surrogate_topk_overlap_summary.csv",
                "manuscript_location": "Supplementary compatibility artifact",
                "role": "Top-K overlap subset retained for backward compatibility with earlier packages",
                "reproducibility_level": "Derived mechanically from surrogate_fidelity_summary.csv",
                "package_boundary": "Included for audit continuity; not a separate experiment.",
            },
            {
                "artifact": "mean_sensitivity_summary.csv",
                "manuscript_location": "Supplementary Section 7 diagnostic",
                "role": "Supporting diagnostic showing sensitivity is largest near the cutoff",
                "reproducibility_level": "Archived calibration summary materialized by archived_diagnostic_tables.py",
                "package_boundary": "The package includes the summarized diagnostic, not the full earlier calibration replay.",
            },
            {
                "artifact": "scale_comparative_summary.csv",
                "manuscript_location": "Supplementary Section 7 diagnostic",
                "role": "Supporting diagnostic for how scale and catalog depth affect the proxy gap",
                "reproducibility_level": "Archived calibration summary materialized by archived_diagnostic_tables.py",
                "package_boundary": "The package includes the summarized diagnostic, not the full earlier calibration replay.",
            },
            {
                "artifact": "covariance_sensitivity_summary.csv",
                "manuscript_location": "Supplementary Section 7 diagnostic",
                "role": "Supporting diagnostic for correlated-prior comparative statics",
                "reproducibility_level": "Archived calibration summary materialized by archived_diagnostic_tables.py",
                "package_boundary": "The package includes the summarized diagnostic, not the full earlier calibration replay.",
            },
            {
                "artifact": "factorization_diagnostic_summary.csv",
                "manuscript_location": "Supplementary Section 7 diagnostic",
                "role": "Diagnostic for treating EIS as a screening rule outside exact factorization",
                "reproducibility_level": "Archived calibration summary materialized by archived_diagnostic_tables.py",
                "package_boundary": "The package includes the summarized diagnostic; EIS format screening itself has raw output in eis_format_validation_raw.csv.",
            },
        ],
    )

    surrogate_rows = [
        {"scale": "2", "N_i": 10, "rmse": 0.058, "mae": 0.046, "pearson_corr": 0.9989, "topk_overlap": 0.95},
        {"scale": "2", "N_i": 100, "rmse": 0.047, "mae": 0.024, "pearson_corr": 0.9994, "topk_overlap": 0.99},
        {"scale": "2", "N_i": 1000, "rmse": 0.024, "mae": 0.012, "pearson_corr": 0.9999, "topk_overlap": 1.00},
        {"scale": "5", "N_i": 10, "rmse": 0.042, "mae": 0.026, "pearson_corr": 0.9997, "topk_overlap": 0.99},
        {"scale": "5", "N_i": 100, "rmse": 0.034, "mae": 0.011, "pearson_corr": 0.9997, "topk_overlap": 0.99},
        {"scale": "5", "N_i": 1000, "rmse": 0.0097, "mae": 0.0039, "pearson_corr": 0.99998, "topk_overlap": 1.00},
        {"scale": "infinity", "N_i": 10, "rmse": 0.000, "mae": 0.000, "pearson_corr": 1.000, "topk_overlap": 1.00},
        {"scale": "infinity", "N_i": 100, "rmse": 0.000, "mae": 0.000, "pearson_corr": 1.000, "topk_overlap": 1.00},
        {"scale": "infinity", "N_i": 1000, "rmse": 0.000, "mae": 0.000, "pearson_corr": 1.000, "topk_overlap": 1.00},
    ]
    write_csv(
        output_dir,
        "surrogate_fidelity_summary.csv",
        ["scale", "N_i", "rmse", "mae", "pearson_corr", "topk_overlap"],
        surrogate_rows,
    )
    write_csv(
        output_dir,
        "surrogate_topk_overlap_summary.csv",
        ["scale", "N_i", "topk_overlap"],
        [{key: row[key] for key in ("scale", "N_i", "topk_overlap")} for row in surrogate_rows if row["scale"] != "infinity"],
    )

    write_csv(
        output_dir,
        "mean_sensitivity_summary.csv",
        ["distance_to_cutoff", "mean_abs_derivative", "max_abs_derivative", "avg_count"],
        [
            {"distance_to_cutoff": "<=0.10", "mean_abs_derivative": 0.271, "max_abs_derivative": 0.448, "avg_count": 3.2},
            {"distance_to_cutoff": "(0.10,0.30]", "mean_abs_derivative": 0.144, "max_abs_derivative": 0.313, "avg_count": 4.3},
            {"distance_to_cutoff": "(0.30,0.60]", "mean_abs_derivative": 0.092, "max_abs_derivative": 0.324, "avg_count": 7.4},
            {"distance_to_cutoff": ">0.60", "mean_abs_derivative": 0.037, "max_abs_derivative": 0.364, "avg_count": 45.1},
        ],
    )

    write_csv(
        output_dir,
        "scale_comparative_summary.csv",
        ["panel", "N_i", "dimension", "value", "delta"],
        [
            {"panel": "vary_K_fixed_L60", "N_i": 10, "dimension": "K", "value": 2, "delta": 0.241},
            {"panel": "vary_K_fixed_L60", "N_i": 10, "dimension": "K", "value": 6, "delta": 0.218},
            {"panel": "vary_K_fixed_L60", "N_i": 10, "dimension": "K", "value": 20, "delta": 0.168},
            {"panel": "vary_K_fixed_L60", "N_i": 100, "dimension": "K", "value": 2, "delta": 0.089},
            {"panel": "vary_K_fixed_L60", "N_i": 100, "dimension": "K", "value": 6, "delta": 0.070},
            {"panel": "vary_K_fixed_L60", "N_i": 100, "dimension": "K", "value": 20, "delta": 0.048},
            {"panel": "vary_L_fixed_K6", "N_i": 10, "dimension": "L", "value": 20, "delta": 0.095},
            {"panel": "vary_L_fixed_K6", "N_i": 10, "dimension": "L", "value": 60, "delta": 0.218},
            {"panel": "vary_L_fixed_K6", "N_i": 10, "dimension": "L", "value": 200, "delta": 0.966},
            {"panel": "vary_L_fixed_K6", "N_i": 100, "dimension": "L", "value": 20, "delta": 0.020},
            {"panel": "vary_L_fixed_K6", "N_i": 100, "dimension": "L", "value": 60, "delta": 0.070},
            {"panel": "vary_L_fixed_K6", "N_i": 100, "dimension": "L", "value": 200, "delta": 0.352},
        ],
    )

    write_csv(
        output_dir,
        "covariance_sensitivity_summary.csv",
        ["N_i", "delta_rho_0_4", "delta_rho_0_6", "delta_rho_0_8"],
        [
            {"N_i": 10, "delta_rho_0_4": 0.560, "delta_rho_0_6": 0.637, "delta_rho_0_8": 0.697},
            {"N_i": 30, "delta_rho_0_4": 0.310, "delta_rho_0_6": 0.326, "delta_rho_0_8": 0.399},
            {"N_i": 100, "delta_rho_0_4": 0.085, "delta_rho_0_6": 0.101, "delta_rho_0_8": 0.121},
        ],
    )

    write_csv(
        output_dir,
        "factorization_diagnostic_summary.csv",
        ["prior", "S", "mad", "max_ad"],
        [
            {"prior": "independent", "S": 2, "mad": 0.038, "max_ad": 0.091},
            {"prior": "independent", "S": 3, "mad": 0.023, "max_ad": 0.064},
            {"prior": "independent", "S": 5, "mad": 0.041, "max_ad": 0.106},
            {"prior": "ar1_rho_0_6", "S": 2, "mad": 0.040, "max_ad": 0.092},
            {"prior": "ar1_rho_0_6", "S": 3, "mad": 0.024, "max_ad": 0.064},
            {"prior": "ar1_rho_0_6", "S": 5, "mad": 0.044, "max_ad": 0.107},
        ],
    )


if __name__ == "__main__":
    main()
